{"name": "test_wrong_pwd", "status": "broken", "statusDetails": {"message": "TypeError: not all arguments converted during string formatting", "trace": "self = <test_case.Login_case.TestLogin object at 0x000002C00B540790>\n\n    @allure.story(\"参数填写不正确，登录失败\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.description(\"密码输入6次错误\")\n    def test_wrong_pwd(self):\n        forbid_5_min = False\n        retry_times = 0\n    \n        for i in range(10):\n            retry_times += 1\n            forbid_5_min = sendWrongLoginRequest()\n            if forbid_5_min:\n                break\n    \n        if not forbid_5_min:\n            logger.error(\"Error! 没有触发等待 5 分钟\")\n            return\n    \n        if not retry_times == 6:\n>           logger.error(\"Error! 没有在第6次错误禁止登录, 次数为\", retry_times)\n\n..\\test_case\\Login_case.py:319: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1463: in error\n    self._log(ERROR, msg, args, **kwargs)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1577: in _log\n    self.handle(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1587: in handle\n    self.callHandlers(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1649: in callHandlers\n    hdlr.handle(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:948: in handle\n    self.emit(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\logging.py:331: in emit\n    super().emit(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1087: in emit\n    self.handleError(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1079: in emit\n    msg = self.format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:923: in format\n    return fmt.format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\logging.py:92: in format\n    return super().format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:659: in format\n    record.message = record.getMessage()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <LogRecord: run_all_case.py, 40, C:\\Users\\张铁瀛\\PycharmProjects\\api aoto\\test_case\\Login_case.py, 319, \"Error! 没有在第6次错误禁止登录, 次数为\">\n\n    def getMessage(self):\n        \"\"\"\n        Return the message for this LogRecord.\n    \n        Return the message for this LogRecord after merging any user-supplied\n        arguments with the message.\n        \"\"\"\n        msg = str(self.msg)\n        if self.args:\n>           msg = msg % self.args\nE           TypeError: not all arguments converted during string formatting\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:363: TypeError"}, "description": "密码输入6次错误", "attachments": [{"name": "stdout", "source": "b25d690f-c7c6-4ae1-b44b-8a9d790ac8fc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1b29302c-fce9-4e8e-bd68-a4866acd2cfe-attachment.txt", "type": "text/plain"}], "start": 1629186775698, "stop": 1629186775826, "uuid": "37bc4a2c-31bf-4668-b292-26d8356261d2", "historyId": "7b9480ebb1961c7c14cb69cc7e65ba50", "testCaseId": "e4c5762512a76c681290f066bcc0e861", "fullName": "test_case.Login_case.TestLogin#test_wrong_pwd", "labels": [{"name": "story", "value": "参数填写不正确，登录失败"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "Login_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KSOAST3"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.Login_case"}]}