{"name": "test_wrong_pwd", "status": "broken", "statusDetails": {"message": "TypeError: not all arguments converted during string formatting", "trace": "self = <test_case.Login_case.TestLogin object at 0x000001DA437B2430>\n\n    @allure.story(\"参数填写不正确，登录失败\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.description(\"密码输入6次错误\")\n    def test_wrong_pwd(self):\n        def_name = sys._getframe().f_code.co_name\n        # test_assert = Assert.Assertions(def_name)\n        logger.info(\"开始执行脚本%s：\\n\", def_name)\n        forbid_5_min = False\n        retry_times = 0\n    \n        for i in range(10):\n            forbid_5_min = sendWrongLoginRequest()\n            if not forbid_5_min:\n                retry_times += 1\n            # if forbid_5_min:\n            #     break\n            time.sleep(0.5)\n    \n        if not forbid_5_min:\n            logger.error(\"Error! 没有触发等待 5 分钟\")\n            return\n    \n        if not retry_times == 6:\n>           logger.error(\"Error! 没有在第6次错误禁止登录, 次数为\", retry_times)\n\n..\\test_case\\Login_case.py:326: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1463: in error\n    self._log(ERROR, msg, args, **kwargs)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1577: in _log\n    self.handle(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1587: in handle\n    self.callHandlers(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1649: in callHandlers\n    hdlr.handle(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:948: in handle\n    self.emit(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\logging.py:331: in emit\n    super().emit(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1087: in emit\n    self.handleError(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:1079: in emit\n    msg = self.format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:923: in format\n    return fmt.format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\logging.py:92: in format\n    return super().format(record)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:659: in format\n    record.message = record.getMessage()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <LogRecord: run_all_case.py, 40, C:\\Users\\张铁瀛\\PycharmProjects\\api aoto\\test_case\\Login_case.py, 326, \"Error! 没有在第6次错误禁止登录, 次数为\">\n\n    def getMessage(self):\n        \"\"\"\n        Return the message for this LogRecord.\n    \n        Return the message for this LogRecord after merging any user-supplied\n        arguments with the message.\n        \"\"\"\n        msg = str(self.msg)\n        if self.args:\n>           msg = msg % self.args\nE           TypeError: not all arguments converted during string formatting\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py:363: TypeError"}, "description": "密码输入6次错误", "attachments": [{"name": "log", "source": "c400de60-c9e8-4c29-8202-012581c1a410-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d0d365fe-dc21-4b45-9695-c280a8a2413e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "79f4fb93-5db4-4c21-ad30-dc8a91b58c3f-attachment.txt", "type": "text/plain"}], "start": 1632469659262, "stop": 1632469666373, "uuid": "0ed04635-98b4-41c0-a325-7fa1b1ca9ab2", "historyId": "7b9480ebb1961c7c14cb69cc7e65ba50", "testCaseId": "e4c5762512a76c681290f066bcc0e861", "fullName": "test_case.Login_case.TestLogin#test_wrong_pwd", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "参数填写不正确，登录失败"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "Login_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KSOAST3"}, {"name": "thread", "value": "11460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.Login_case"}]}