Fri, 24 Sep 2021 15:52:44-run_all_case.py-Login_case.py-[line:309]-INFO-[日志信息]: 开始执行脚本test_wrong_pwd：

Fri, 24 Sep 2021 15:52:44-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=0, msg=手机号或密码错误，请重试.

Fri, 24 Sep 2021 15:52:45-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=1, msg=手机号或密码错误，请重试.

Fri, 24 Sep 2021 15:52:46-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=2, msg=手机号或密码错误，请重试.

Fri, 24 Sep 2021 15:52:47-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=3, msg=手机号或密码错误，请重试.

Fri, 24 Sep 2021 15:52:47-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=4, msg=手机号或密码错误，请重试.

Fri, 24 Sep 2021 15:52:48-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=5, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Fri, 24 Sep 2021 15:52:49-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=6, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Fri, 24 Sep 2021 15:52:49-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=7, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Fri, 24 Sep 2021 15:52:50-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=8, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Fri, 24 Sep 2021 15:52:51-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=9, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

