INFO     run_all_case.py:Register_case.py:160 开始执行脚本test_Pwd_Error：