INFO     run_all_case.py:test_RegisterCase.py:28 当前用例名称：密码输入17位
INFO     run_all_case.py:test_RegisterCase.py:29 当前测试用例请求参数：{'password': '12345678901234567', 'phone': '18937524610', 'v_code': '666666'}
INFO     run_all_case.py:test_RegisterCase.py:30 当前用例预期结果：{'code': 'InternalError', 'msg': '验证码无效，请重新获取'}
INFO     run_all_case.py:test_RegisterCase.py:31 当前用例实际结果：{'code': 'AlreadyExist', 'data': None, 'msg': '手机号已注册', 'debug_error': ''}

ERROR    run_all_case.py:Assert.py:110 Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'AlreadyExist' == 'InternalError'
  - InternalError
  + AlreadyExist

ERROR    run_all_case.py:test_RegisterCase.py:36 用例执行失败assert 'AlreadyExist' == 'InternalError'
  - InternalError
  + AlreadyExist