Tue, 12 Apr 2022 19:25:17-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2022-04-12 19:25:17===================================
Tue, 12 Apr 2022 19:25:25-run_all_case.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'RecordNotFoundError' == 'Success'
  - Success
  + RecordNotFoundError

Tue, 12 Apr 2022 19:25:32-run_all_case.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'InternalError' == 'Success'
  - Success
  + InternalError

Tue, 12 Apr 2022 19:25:39-run_all_case.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'WxClientError' == 'BadRequest'
  - BadRequest
  + WxClientError

Tue, 12 Apr 2022 19:25:41-run_all_case.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'Success' == 'BadRequest'
  - BadRequest
  + Success

Tue, 12 Apr 2022 19:25:47-run_all_case.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'Success' == 'BadRequest'
  - BadRequest
  + Success

Tue, 12 Apr 2022 19:25:49-run_all_case.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'Success' == 'BadRequest'
  - BadRequest
  + Success

Tue, 12 Apr 2022 19:29:02-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'RecordNotFoundError' == 'Success'

Tue, 12 Apr 2022 19:30:52-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'ServerError' == 'Success'

